name: harvard_image_encoder

inference_map:
  image_path:
    forward_model_name: ct_fm_image_encoder
    compress: True
    output_field: z_image
  ct_fm_image_encoder/z_image:
    forward_model_name: identity
    compress: False
    output_field: multimodal_embedding
