name: merlin_longformer

inference_map:
  findings:
    forward_model_name: merlin_text_encoder
    compress: True
    output_field: z_findings
  merlin_text_encoder/z_findings:
    forward_model_name: identity
    compress: False
    output_field: multimodal_embedding