# wandb_sweep_id: t3qho6x5
wandb_sweep_id: hzirxies

outcome: 'test_auc_epoch'

data_order: ['1_phecodes_abdominal_ct', '2_multimodal_abdominal_ct_text', '3_multimodal_abdominal_ct_image', '4_multimodal_abdominal_ct_image_text']
