# outputs: ['aortic_valve_calcification']
outputs: ['splenomegaly']
# outputs: ['ost']
# outputs: ['htn']
# outputs: ['ckd', 'ost', 'htn', 'ihd', 'dm', 'cvd']

output_filter: [0, 1]

batch_size: 2
num_outs: 1


predictor_path: MultimodalMedicalHG/LinearEvaluation/no_sweep/multimodal_abdominal_ct_image_text/