defaults:
  - _self_
  - paths: stanford
  - multimodal_pretraining: default
  - sparse_autoencoder: basic
  - data: abdominal_ct
  - task: prognosis

wandb_api_token: ${paths.wandb_api_token}
wandb_project: 'MultimodalMedicalHG'
wandb_mode: online
wandb_log_frequency: 1
wandb_entity: ${paths.wandb_entity}

seed: 1234
pretrained_model_dir: ${paths.pretrained_model_dir}

base_dir: ${paths.base_dir}

model_name: identity